# Generated by Django 4.1.3 on 2022-12-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
