# Generated by Django 4.1.3 on 2022-12-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dars', '0003_python'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=60)),
                ('add_date', models.DateTimeField()),
                ('kurs', models.CharField(blank=True, choices=[('C++', 'C++'), ('Java', 'Java'), ('Javascript', 'Javascript')], max_length=10)),
            ],
        ),
    ]
