# Generated by Django 4.1.3 on 2022-12-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dars', '0004_ftf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yangi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=60)),
                ('add_date', models.DateTimeField()),
                ('kurs', models.CharField(blank=True, choices=[('Samarqand', 'Samarqand'), ('Toshkent', 'Toshkent'), ('Buxoro', 'Buxoro')], max_length=10)),
            ],
        ),
    ]
