# Generated by Django 4.1.3 on 2022-12-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dars', '0006_yangi_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yangi',
            old_name='img',
            new_name='imgsss',
        ),
    ]
