# Generated by Django 4.1.3 on 2022-12-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dars', '0007_rename_img_yangi_imgsss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yangi',
            old_name='kurs',
            new_name='Shaharlar',
        ),
    ]
